spring:
  datasource:
    url: jdbc:mysql://localhost/drivers
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto:  none
server:
  port: 8081
